# Generated by Django 3.2.4 on 2021-06-17 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cust_acc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.TextField(max_length=225)),
                ('token', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cust_store',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('number', models.BigIntegerField()),
                ('address', models.TextField(max_length=255)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.cust_acc')),
            ],
        ),
        migrations.CreateModel(
            name='Product_info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mrp', models.FloatField()),
                ('sele_price', models.FloatField()),
                ('image', models.FileField(upload_to='products/')),
                ('discription', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.category')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.cust_acc')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.cust_store')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product_info')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.cust_acc')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.cust_store')),
            ],
        ),
    ]
