# Generated by Django 3.2.4 on 2021-06-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_store',
            name='mail',
            field=models.EmailField(default='store@gmail.com', max_length=30),
        ),
    ]
